--- #YAML:1.0
name:               CGI-Application-Plugin-Menu
version:            1.06
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              1
    CGI::Application:  4.06
    Exporter:          5
    HTML::Template:    2.9
    LEOCHARRE::DEBUG:  1.13
    Smart::Comments:   1
    Test::Simple:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
